### ISSUE TITLE
May I know the details of generating rec files of Cifar100 and Imagenet?

### ISSUE THREAD

**Issue by woshichase** [hellozting/InterleavedGroupConvolutions#2]
Hi! I am now running ur code and generating rec files of the dataset myself. In order to keep the same rec file with yours, may I know the following details:
1. When generating Cifar100 rec file, what quality(0-100, default quality is 95) did you set with im2rec.py?
2. When generating Imagenet rec file, what quality did you set with im2rec.py and did you do resize step (such as resize to 256) with im2rec?

**Comment by hellozting** [comment]
Hi, 

For CIFAR100, I downloaded the rec file from the mxnet official website.
For ImageNet, the quality is set to 95 and the size is resized to 256.

Thanks,

**Comment by woshichase** [comment]
Thank you!

**Comment by hellozting** [comment]
Hi, 

Correct the ImageNet data preparation. 
The ImageNet data is resized to 480 (the short side) with aspect ratio keeped. And the data augmentation can be found in the train_imagenet.py file. Sorry for the misinformation.

Thanks,
